name: "whisper_large_v3"
backend: "python"
max_batch_size: 0

input [
  { name: "AUDIO_B64" data_type: TYPE_STRING dims: [1] },
  { name: "MODE" data_type: TYPE_STRING dims: [1] },
  { name: "OUTPUT_FORMAT" data_type: TYPE_STRING dims: [1] },
  { name: "LANGUAGE" data_type: TYPE_STRING dims: [1] },
  { name: "BEAM_SIZE" data_type: TYPE_INT32 dims: [1] },
  { name: "TEMPERATURE" data_type: TYPE_FP32 dims: [1] },
  { name: "VAD_FILTER" data_type: TYPE_INT32 dims: [1] }
]

output [
  { name: "OUTPUT" data_type: TYPE_STRING dims: [1] },
  { name: "INFERENCE_TIME_SEC" data_type: TYPE_FP32 dims: [1] }
]
