name: "whisper_large_v3"
backend: "python"
max_batch_size: 0

instance_group [
  { kind: KIND_MODEL count: 1 }
]

parameters: {
  key: "WHISPER_MODEL"
  value: { string_value: "large-v3" }
}

input [
  { name: "AUDIO_B64"       data_type: TYPE_STRING dims: [1] },

  { name: "MODE"            data_type: TYPE_STRING dims: [1] },
  { name: "LANGUAGE"        data_type: TYPE_STRING dims: [1] },

  { name: "BEAM_SIZE"       data_type: TYPE_INT32  dims: [1] },
  { name: "TEMPERATURE"     data_type: TYPE_FP32   dims: [1] },
  { name: "VAD_FILTER"      data_type: TYPE_INT32  dims: [1] },
  { name: "WORD_TIMESTAMPS" data_type: TYPE_INT32  dims: [1] },

  { name: "RETURN_SRT"      data_type: TYPE_INT32  dims: [1] },
  { name: "RETURN_VTT"      data_type: TYPE_INT32  dims: [1] }
]

output [
  { name: "TEXT"              data_type: TYPE_STRING dims: [1] },
  { name: "SEGMENTS"          data_type: TYPE_STRING dims: [1] },
  { name: "SRT"               data_type: TYPE_STRING dims: [1] },
  { name: "VTT"               data_type: TYPE_STRING dims: [1] },
  { name: "INFERENCE_TIME_SEC" data_type: TYPE_FP32 dims: [1] }
]
